// <auto-generated />
using System;
using Investissement_WebClient.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investissement_WebClient.Infrastructure.Migrations
{
    [DbContext(typeof(InvestissementDbContext))]
    [Migration("20260820065841_RelationUnUnUtilisateurUtilisateurPowens")]
    partial class RelationUnUnUtilisateurUtilisateurPowens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.Actif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)")
                        .IsFixedLength();

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actif");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.Banque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConnectionPowens")
                        .HasColumnType("int");

                    b.Property<int>("IdConnectorPowens")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurPowensId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("UtilisateurPowensId");

                    b.ToTable("Banque");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.CategorieFlux", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MacroCategorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MicroCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategorieFlux");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Alimentation"
                        },
                        new
                        {
                            Id = 2,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Achat de nécéssité"
                        },
                        new
                        {
                            Id = 4,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Sport"
                        },
                        new
                        {
                            Id = 5,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Abonnement fixe"
                        },
                        new
                        {
                            Id = 6,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Logement"
                        },
                        new
                        {
                            Id = 7,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Santé"
                        },
                        new
                        {
                            Id = 8,
                            MacroCategorie = "Revenus",
                            MicroCategorie = "Salaire"
                        },
                        new
                        {
                            Id = 9,
                            MacroCategorie = "Revenus",
                            MicroCategorie = "Aide"
                        },
                        new
                        {
                            Id = 10,
                            MacroCategorie = "Revenus",
                            MicroCategorie = "Cadeau reçu"
                        },
                        new
                        {
                            Id = 11,
                            MacroCategorie = "Patrimoine",
                            MicroCategorie = "Investissement TR"
                        },
                        new
                        {
                            Id = 12,
                            MacroCategorie = "Patrimoine",
                            MicroCategorie = "Investissement AV"
                        },
                        new
                        {
                            Id = 13,
                            MacroCategorie = "Patrimoine",
                            MicroCategorie = "Epargne"
                        },
                        new
                        {
                            Id = 14,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Achat plaisir"
                        },
                        new
                        {
                            Id = 15,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Vacances"
                        },
                        new
                        {
                            Id = 16,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Abonnement plaisir"
                        },
                        new
                        {
                            Id = 17,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Achat cadeau"
                        },
                        new
                        {
                            Id = 18,
                            MicroCategorie = "Autre"
                        },
                        new
                        {
                            Id = 19,
                            MacroCategorie = "Livret A",
                            MicroCategorie = "Livret A"
                        });
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.CompteBanque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BanqueId")
                        .HasColumnType("int");

                    b.Property<int>("IdComptePowens")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePowens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BanqueId");

                    b.ToTable("CompteBanque");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.FluxBancaire", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CompteBanqueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Suggestion")
                        .HasColumnType("bit");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompteBanqueId");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("FluxBancaire");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.FluxInvestissement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActifId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Frais")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActifId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("FluxInvestissement");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.TradeRepublicAcces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NumTelCrypte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCrypte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("TradeRepublicAcces");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreationCompte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MdpHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.UtilisateurPowens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessTokenCrypte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUtilisateurPowens")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("UtilisateurPowens");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.ValeurPatrimoine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvestissementTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ValeurPatrimoine");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.Banque", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.Utilisateur", null)
                        .WithMany("BanquesAcces")
                        .HasForeignKey("UtilisateurId");

                    b.HasOne("Investissement_WebClient.Domain.Modeles.UtilisateurPowens", "UtilisateurPowens")
                        .WithMany("Banques")
                        .HasForeignKey("UtilisateurPowensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UtilisateurPowens");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.CompteBanque", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.Banque", "Banque")
                        .WithMany("Comptes")
                        .HasForeignKey("BanqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banque");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.FluxBancaire", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.CompteBanque", "CompteBanque")
                        .WithMany()
                        .HasForeignKey("CompteBanqueId");

                    b.HasOne("Investissement_WebClient.Domain.Modeles.CategorieFlux", "Categorie")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Investissement_WebClient.Domain.Modeles.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("CompteBanque");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.FluxInvestissement", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.Actif", "Actif")
                        .WithMany()
                        .HasForeignKey("ActifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investissement_WebClient.Domain.Modeles.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actif");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.TradeRepublicAcces", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.UtilisateurPowens", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.Utilisateur", "Utilisateur")
                        .WithOne("UtilisateurPowens")
                        .HasForeignKey("Investissement_WebClient.Domain.Modeles.UtilisateurPowens", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.ValeurPatrimoine", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.Banque", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.Utilisateur", b =>
                {
                    b.Navigation("BanquesAcces");

                    b.Navigation("UtilisateurPowens");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.UtilisateurPowens", b =>
                {
                    b.Navigation("Banques");
                });
#pragma warning restore 612, 618
        }
    }
}
