// <auto-generated />
using System;
using Investissement_WebClient.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investissement_WebClient.Infrastructure.Migrations
{
    [DbContext(typeof(InvestissementDbContext))]
    [Migration("20260512173756_MAJNomTables")]
    partial class MAJNomTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.BanqueAcces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccesToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCompteCourant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BanqueAcces");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.CategorieFlux", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MacroCategorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MicroCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategorieFlux");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Alimentation"
                        },
                        new
                        {
                            Id = 2,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Transport"
                        },
                        new
                        {
                            Id = 4,
                            MicroCategorie = "Livret A"
                        },
                        new
                        {
                            Id = 5,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Achat de nécéssité"
                        },
                        new
                        {
                            Id = 6,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Sport"
                        },
                        new
                        {
                            Id = 7,
                            MacroCategorie = "Revenus",
                            MicroCategorie = "Salaire"
                        },
                        new
                        {
                            Id = 8,
                            MacroCategorie = "Revenus",
                            MicroCategorie = "Aide"
                        },
                        new
                        {
                            Id = 9,
                            MacroCategorie = "Autre",
                            MicroCategorie = "Autre"
                        },
                        new
                        {
                            Id = 10,
                            MacroCategorie = "Patrimoine",
                            MicroCategorie = "Investissement TR"
                        },
                        new
                        {
                            Id = 11,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Abonnement fixe"
                        },
                        new
                        {
                            Id = 12,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Logement"
                        },
                        new
                        {
                            Id = 13,
                            MacroCategorie = "Revenus",
                            MicroCategorie = "Cadeau reçu"
                        },
                        new
                        {
                            Id = 14,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Achat plaisir"
                        },
                        new
                        {
                            Id = 15,
                            MacroCategorie = "Patrimoine",
                            MicroCategorie = "Investissement AV"
                        },
                        new
                        {
                            Id = 16,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Vacances"
                        },
                        new
                        {
                            Id = 17,
                            MacroCategorie = "Vie quotidienne",
                            MicroCategorie = "Santé"
                        },
                        new
                        {
                            Id = 18,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Abonnement plaisir"
                        },
                        new
                        {
                            Id = 19,
                            MacroCategorie = "Patrimoine",
                            MicroCategorie = "Epargne"
                        },
                        new
                        {
                            Id = 20,
                            MacroCategorie = "Loisirs/Plaisirs",
                            MicroCategorie = "Achat cadeau"
                        });
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.FluxBancaire", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<string>("LibelleRecu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorie");

                    b.ToTable("FluxBancaire");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.FluxInvestissement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Actif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Frais")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ISIN")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)")
                        .IsFixedLength();

                    b.Property<decimal?>("Prix")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Quantite")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FluxInvestissement");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.ValeurPatrimoine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvestissementTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ValeurPatrimoine");
                });

            modelBuilder.Entity("Investissement_WebClient.Domain.Modeles.FluxBancaire", b =>
                {
                    b.HasOne("Investissement_WebClient.Domain.Modeles.CategorieFlux", "Categorie")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
