// <auto-generated />
using System;
using Investissement_WebClient.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investissement_WebClient.Data.Migrations
{
    [DbContext(typeof(InvestissementDbContext))]
    [Migration("20260426170856_AjoutCategories")]
    partial class AjoutCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.CategorieFlux", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategorieFlux");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "Alimentation"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "Avance Livret A"
                        },
                        new
                        {
                            Id = 4,
                            Libelle = "Dette Livret A"
                        },
                        new
                        {
                            Id = 5,
                            Libelle = "Shopping"
                        },
                        new
                        {
                            Id = 6,
                            Libelle = "Sport"
                        },
                        new
                        {
                            Id = 7,
                            Libelle = "Salaire"
                        },
                        new
                        {
                            Id = 8,
                            Libelle = "APL"
                        },
                        new
                        {
                            Id = 9,
                            Libelle = "Autre"
                        },
                        new
                        {
                            Id = 10,
                            Libelle = "Investissement Trade Republic"
                        },
                        new
                        {
                            Id = 11,
                            Libelle = "Abonnement"
                        },
                        new
                        {
                            Id = 12,
                            Libelle = "Logement"
                        },
                        new
                        {
                            Id = 13,
                            Libelle = "Cadeaux"
                        },
                        new
                        {
                            Id = 14,
                            Libelle = "Achat plaisir"
                        },
                        new
                        {
                            Id = 15,
                            Libelle = "Investissement AV"
                        },
                        new
                        {
                            Id = 16,
                            Libelle = "Vacances"
                        },
                        new
                        {
                            Id = 17,
                            Libelle = "Santé"
                        });
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.CreditCoopAcces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccesToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CreditCoopAcces");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.FluxCreditCoop", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<string>("LibelleRecu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorie");

                    b.ToTable("FluxCreditCoop");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.FluxTradeRepublic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Expediteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FluxTradeRepublic");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.HistoriquePatrimoine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvestissementTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HistoriquePatrimoine");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Actif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Frais")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ISIN")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)")
                        .IsFixedLength();

                    b.Property<decimal?>("Prix")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Quantite")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.FluxCreditCoop", b =>
                {
                    b.HasOne("Investissement_WebClient.Core.Modeles.CategorieFlux", "Categorie")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
