// <auto-generated />
using System;
using Investissement_WebClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investissement_WebClient.Data.Migrations
{
    [DbContext(typeof(InvestissementDbContext))]
    [Migration("20260303184559_InitialCreateSqlServer")]
    partial class InitialCreateSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Actif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Risque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasFilter("[Isin] IS NOT NULL");

                    b.ToTable("Actifs");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.ActifEnregistre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("nchar(12)")
                        .IsFixedLength();

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Risque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasFilter("[Isin] IS NOT NULL");

                    b.ToTable("ActifEnregistres");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.CompositionModele", b =>
                {
                    b.Property<int>("IdActifEnregistre")
                        .HasColumnType("int");

                    b.Property<int>("IdModele")
                        .HasColumnType("int");

                    b.Property<double?>("Quantite")
                        .HasColumnType("float");

                    b.HasKey("IdActifEnregistre", "IdModele");

                    b.HasIndex("IdModele");

                    b.ToTable("CompositionModeles");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.HistoriquePatrimoine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("InvestissementTotal")
                        .HasColumnType("float");

                    b.Property<double>("Valeur")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HistoriquePatrimoine");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Investissement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateInvest")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdModele")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdModele");

                    b.ToTable("Investissements");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Modele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Modeles");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Frais")
                        .HasColumnType("float");

                    b.Property<int>("IdActifEnregistre")
                        .HasColumnType("int");

                    b.Property<int>("IdInvestissement")
                        .HasColumnType("int");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<double>("Quantite")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdActifEnregistre");

                    b.HasIndex("IdInvestissement");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.CompositionModele", b =>
                {
                    b.HasOne("Investissement_WebClient.Core.Modeles.ActifEnregistre", "ActifEnregistre")
                        .WithMany("Composition")
                        .HasForeignKey("IdActifEnregistre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investissement_WebClient.Core.Modeles.Modele", "Modele")
                        .WithMany("Composition")
                        .HasForeignKey("IdModele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActifEnregistre");

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Investissement", b =>
                {
                    b.HasOne("Investissement_WebClient.Core.Modeles.Modele", "Modele")
                        .WithMany("Investissements")
                        .HasForeignKey("IdModele");

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Transaction", b =>
                {
                    b.HasOne("Investissement_WebClient.Core.Modeles.ActifEnregistre", "ActifEnregistre")
                        .WithMany("Transactions")
                        .HasForeignKey("IdActifEnregistre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investissement_WebClient.Core.Modeles.Investissement", "Investissement")
                        .WithMany("Transactions")
                        .HasForeignKey("IdInvestissement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActifEnregistre");

                    b.Navigation("Investissement");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.ActifEnregistre", b =>
                {
                    b.Navigation("Composition");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Investissement", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Investissement_WebClient.Core.Modeles.Modele", b =>
                {
                    b.Navigation("Composition");

                    b.Navigation("Investissements");
                });
#pragma warning restore 612, 618
        }
    }
}
